version: '3.1'
services:
  db:
    image: mysql
    build: .
    container_name: fatec_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fatec_db
    ports:
      - "3306:3306"
    volumes:
      - /Fatec/desenvolvimentoweb.sql